#!/bin/sh
rm -f ./result
. ./package_files/config
export PORTS=$PORTS
t=0

for i in `ls ../ports`;do
	case $i in
		*-32)
			ti="${i%-32}";;
		*)
			ti="$i";;
	esac
	case $ti in
		freetype-hf) continue;;
		gettext-tiny|filesystem|zzz|slstatus|twmn|clew|curmix|pclcmd|libcorkipset|qtstyleplugins|pixiewps|reaver)
			wait
			pkg -M $i || exit
			pkg -S $i || exit
			;;
		xorg-proto|xorg-app|xorg-fonts)
			./.c$i &;;
		glog)
			./.carch ../ports $i google-glog &;;
		spice-gtk)
			./.carch ../ports $i spice-gtk3 &;;
		python-enum34)
			./.carch ../ports $i python2-enum34 &;;
		python-ipaddress)
			./.carch ../ports $i python2-ipaddress &;;
		python)
			./.carch ../ports $i python2 &;;
		python3)
			./.carch ../ports $i python &;;
		netcat)
			./.carch ../ports $i gnu-netcat &;;
		freetype|glib)
			./.carch ../ports $i ${ti}2 &;;
		minizip)
			./.carch ../ports $i zlib &;;
		perl-glib-object-introspection)
			./.caur ../ports $i https://aur.archlinux.org/packages/perl-glib-object-introspection/ &;;
		pixiewps)
			./.caur ../ports $i https://aur.archlinux.org/packages/pixiewps/ &;;
		tbb)
			./.carch ../ports $i intel-tbb &;;
		qt5)
			./.carch ../ports $i qt5-base &;;
		qt4-webkit)
			./.carch ../ports $i qtwebkit  &;;
		util-macros)
			./.carch ../ports $i xorg-$ti  &;;
		p5-xml-parser)
			./.carch ../ports $i perl-xml-parser  &;;
		libpcre)
			./.carch ../ports $i pcre  &;;
		libgmp)
			./.carch ../ports $i gmp  &;;
		libxscrnsaver)
			./.carch ../ports $i libxss  &;;
		proxychains)
			./.carch ../ports $i ${ti}-ng  &;;
		python-cython)
			./.carch ../ports $i cython &;;
		glfw)
			./.carch ../ports $i $ti-x11 &;;
		rxvt)
			./.carch ../ports $i $ti-unicode &;;
		linux|linux-x86_64|linux-headers)
			./.carch ../ports $i linux-zen &;;
		python-pygmentize)
			./.carch ../ports $i pygmentize &;;
		gtk)
			./.carch ../ports $i gtk2 &;;
		phonon)
			./.carch ../ports $i phonon-qt5 &;;
		linux-tools)
			./.carch ../ports $i linux-tools-meta &;;
		man-pages-zh)
			./.carch ../ports $i man-pages-zh_CN &;;
		graphite2)
			./.carch ../ports $i graphite &;;
		adobe-source-han-sans-fonts-zh)
			./.carch ../ports $i adobe-source-han-sans-cn-fonts &;;
		wine)
			./.caur ../ports $i https://aur.archlinux.org/packages/wine-gaming-nine &;;
		ttf-mononoki)
			./.caur ../ports $i https://aur.archlinux.org/packages/ttf-mononoki &;;
		fortify-headers|argp-standalone|libc-dev|texlive|fftw)
			./.calpine ../ports $i $ti&;;
		pthread-stubs)
			./.calpine ../ports $i lib$ti&;;
		libc-dev|libressl|gdk-pixbuf|eudev)
			./.calpine ../ports $i $ti &;;
		musl|musl-fts|musl-obstack|ca-certificates|opencollada)
			./.cvoid ../ports "$i" "$ti" &;;
		ttf-noto-emoji)
			./.cvoid ../ports "$i" "noto-fonts-emoji" &;;
		libmpfr)
			./.carch ../ports "$i" "mpfr" &;;
		finit|libuev|libite)
			echo "$i: check manually!" >> result;;
		arc-theme)
			./.carch ../ports $i arc-gtk-theme &;;
		arc-icon)
			./.carch ../ports $i arc-icon-theme &;;
		*)
			./.carch ../ports "$i" "$ti" &;;
	esac
	t=$((t+1))
	if [ $t -eq 10 ]; then
		wait
	fi
done
wait
cat result | sort -k 2 > s
rm result
mv s result
