#!/bin/sh
set -e
export PKG_CONFIG=`pwd`/package_files/config
export SYSROOT=`pwd`/noname

# clean
umount -R ./noname/* ./noname/etc/resolv.conf >/dev/null 2>&1 || true
rm -rf ./noname

# install noname
echo ":: building rootfs"
cat lists_of_base | while read i; do
	yes | pkg --root $SYSROOT --config $PKG_CONFIG -S $i || exit
done

tar czf noname_`date +%Y%m`.tar.gz noname

# clear
rm -rf ./noname
