#!/bin/sh
rm -f reloc
find /lib -type f -exec ldd {} 2>&1 \; | grep 'Error loading shared library' | sed 's/^Error loading shared library //g' | uniq > reloc
find /lib32 -type f -exec ldd {} 2>&1 \; | grep 'Error loading shared library' | sed 's/^Error loading shared library //g' | uniq >> reloc
find /bin -type f -exec ldd {} 2>&1 \; | grep 'Error loading shared library' | sed 's/^Error loading shared library //g' | uniq >> reloc
