#!/bin/sh
set -x
list="`git diff --name-only HEAD~ HEAD | grep metadata | cut -d '/' -f 2`"
for i in $list; do
	sshpass -f ~/scripts/sshpass ssh thunix.org "./rm.sh ${i}#"
	sshpass -f ~/scripts/sshpass scp "`ls ../tarballs/${i}#*tgz`" xhe@thunix.org:/home/x/xhe/www/tarballs
done
